apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-back
  template:
    metadata:
      labels:
        app: web-back
    spec:
      containers:
      - name: web-back
        image: 236747833953.dkr.ecr.ap-northeast-2.amazonaws.com/web:2.23
        ports:
          - containerPort: 8000
        env:
          - name: DATABASE_HOST
            value: db.cv0mjqsao6wx.ap-northeast-2.rds.amazonaws.com
        volumeMounts:
        - name: staticfiles
          mountPath: /code/staticfiles
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      imagePullSecrets:
        - name: ap-northeast-2-ecr-secret
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: web
          image: 236747833953.dkr.ecr.ap-northeast-2.amazonaws.com/nginx:2.04
          ports:
            - containerPort: 3000
            - containerPort: 8000
          volumeMounts:
          - name: staticfiles
            mountPath: /var/www/static
      volumes:
        - name: staticfiles
          persistentVolumeClaim:
            claimName: staticfiles-pvc
      imagePullSecrets:
        - name: ap-northeast-2-ecr-secret
      restartPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-front
  template:
    metadata:
      labels:
        app: web-front
    spec:
      containers:
        - name: web-front
          image: 236747833953.dkr.ecr.ap-northeast-2.amazonaws.com/web-front:2.10
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: ap-northeast-2-ecr-secret
      restartPolicy: Always
